Algoritmo "Múltiplos de 3"

Var

   j: INTEIRO
   numero1, numero2: INTEIRO

Inicio


      escreva ("Digite o primeiro número: ")
      leia (numero1)
      escreva ("Digite o segundo número: ")
      leia (numero2)
      escreval
      para j de numero1 ate numero2 faca
      se (j%3=0) entao
      escreval(j, " é múltiplo de 3")
      senão
      escreval (j, " não é múltiplo de 3")

      
      fimse fimse
      fimpara



Fimalgoritmo